---
title: "2_CellTyping"
author: "Drew"
date: "2024-07-28"
output: html_document
---

```{r}
source("https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/R/gene_sets_prepare.R"); source("https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/R/sctype_score_.R")
library(biomaRt)
library(ComplexHeatmap)
library(dplyr)
library(HGNChelper)
library(openxlsx)
library(grid)
library(gridExtra)
library(Seurat)
library(patchwork)
library(presto)
library(dplyr)
library(gridExtra)
library(grid)
library(ggplot2)
```

```{r}
dat <- readRDS("FinaleProcessedData/QCclusteredDat.rds")
```

### formatting markers list 

```{r}
markersUp <- read.csv("misc/markersUPformat.csv")
markersDown <- read.csv("misc/markersDownformat.csv")


cellTypes <- colnames(markersUp)
gs_positive <- list()
gs_negative <- list()

for (i in cellTypes) {
  gs_positive[[i]] <- toupper(markersUp[[i]])  # Remove NA values
  gs_positive[[i]] <- as.character(na.omit(gs_positive[[i]]))
  gs_negative[[i]] <- toupper(markersDown[[i]])  # Remove NA values
  gs_negative[[i]] <- as.character(na.omit(gs_negative[[i]]))
}

markersList <- list(gs_positive = gs_positive, gs_negative = gs_negative)
```

#### ref paper DE gene markers 

```{r}
refMarkers_All <- read.xlsx("misc/refPaperMarkers_all.xlsx")
refMarkers_All$cluster <- as.character(refMarkers_All$cluster)

refMarkeresList_all <- list()
refMarkeresList_allNeg <- list()
clusIds <- unique(refMarkers_All$cluster)

for (i in clusIds) {
  refMarkeresList_all[[paste0(i, "_ref")]] <- head(refMarkers_All[refMarkers_All$cluster == i &
                                                  refMarkers_All$avg_logFC > 0 ,], 100)
  refMarkeresList_all[[paste0(i, "_ref")]] <- toupper(refMarkeresList_all[[paste0(i, "_ref")]]$gene)
}

names(refMarkeresList_all)[names(refMarkeresList_all) %in% c("0_ref", "4_ref", "9_ref", "15_ref", "17_ref")] <- c("Ductal", "Tumour", "Acinar", "Acinar 2", "metaplastic")
```


### prepping data and running sc-type

```{r}
head(dat@meta.data)

scaledDat <- as.matrix(dat[["RNA"]]$scale.data)
```

#### running sctype - from cell markers list

```{r}
es.max <- as.data.frame(sctype_score(scaledDat, scaled = TRUE, gs = markersList$gs_positive, gs2 = markersList$gs_negative))

heatMapConfList <- list()

# Loop over resolutions 0.5 and 0.7
for (i in c("0.3", "0.5", "0.7", "1")) {

  # Process each unique cluster in the current resolution
  cL_resutls <- do.call("rbind", lapply(unique(dat@meta.data[[paste0("RNA_snn_res.", i)]]), function(cl) {
    # Sort and aggregate scores for the current cluster
    es.max.cl <- sort(rowSums(es.max[, rownames(dat@meta.data[dat@meta.data[[paste0("RNA_snn_res.", i)]] == cl, ])]),
                      decreasing = TRUE)
    head(data.frame(cluster = cl, type = names(es.max.cl), scores = es.max.cl,
                    ncells = sum(dat@meta.data[[paste0("RNA_snn_res.", i)]] == cl)), 38)
  }))

  # Group results by cluster and select top scores
  sctype_scores <- cL_resutls %>% group_by(cluster) %>% top_n(n = 1, wt = scores)

  # Label scores below a threshold as "Unknown"
  sctype_scores$type[as.numeric(as.character(sctype_scores$scores)) < sctype_scores$ncells / 4] <- "Unknown"
  print(sctype_scores[, 1:3])

  head(sctype_scores)

  # Identify low-confidence clusters
  lowConfidenceClusters <- sctype_scores[sctype_scores$scores < 1000, ]
  sctype_scores <- sctype_scores %>%
    mutate(type = ifelse(scores < 1000, paste(type, "lowConf"), type))
  sctype_scores$type <- paste0(sctype_scores$cluster, "_", sctype_scores$type)

  # Assign cluster types to metadata
  dat@meta.data[[paste0("sctype", i)]] <- ""
  for (j in unique(sctype_scores$cluster)) {
    cl_type <- sctype_scores[sctype_scores$cluster == j, ]
    dat@meta.data[[paste0("sctype", i)]][dat@meta.data[[paste0("RNA_snn_res.", i)]] == j] <- as.character(cl_type$type[1])
  }
  
  heatMapConfList[[i]] <- cL_resutls  
  
}

head(dat@meta.data)
```


#### running sctype - from paper reference DE

```{r}
es.max <- as.data.frame(sctype_score(scaledDat, scaled = TRUE, gs = refMarkeresList_all, gs2 = NULL))

heatMapConfListRef <- list()

# Loop over resolutions 0.5 and 0.7
for (i in c("0.3", "0.5", "0.7", "1")) {

  # Process each unique cluster in the current resolution
  cL_resutls <- do.call("rbind", lapply(unique(dat@meta.data[[paste0("RNA_snn_res.", i)]]), function(cl) {
    # Sort and aggregate scores for the current cluster
    es.max.cl <- sort(rowSums(es.max[, rownames(dat@meta.data[dat@meta.data[[paste0("RNA_snn_res.", i)]] == cl, ])]),
                      decreasing = TRUE)
    head(data.frame(cluster = cl, type = names(es.max.cl), scores = es.max.cl,
                    ncells = sum(dat@meta.data[[paste0("RNA_snn_res.", i)]] == cl)), 38)
  }))

  # Group results by cluster and select top scores
  sctype_scores <- cL_resutls %>% group_by(cluster) %>% top_n(n = 1, wt = scores)

  # Label scores below a threshold as "Unknown"
  sctype_scores$type[as.numeric(as.character(sctype_scores$scores)) < sctype_scores$ncells / 4] <- "Unknown"
  print(sctype_scores[, 1:3])

  head(sctype_scores)

  # Identify low-confidence clusters
  lowConfidenceClusters <- sctype_scores[sctype_scores$scores < 1000, ]
  sctype_scores <- sctype_scores %>%
    mutate(type = ifelse(scores < 1000, paste(type, "lowConf"), type))
  sctype_scores$type <- paste0(sctype_scores$cluster, "_", sctype_scores$type)

  # Assign cluster types to metadata
  dat@meta.data[[paste0("sctypeRef", i)]] <- ""
  for (j in unique(sctype_scores$cluster)) {
    cl_type <- sctype_scores[sctype_scores$cluster == j, ]
    dat@meta.data[[paste0("sctypeRef", i)]][dat@meta.data[[paste0("RNA_snn_res.", i)]] == j] <- as.character(cl_type$type[1])
  }

  heatMapConfListRef[[i]] <- cL_resutls
}

head(dat@meta.data)
```

```{r}

umap03 <- DimPlot(dat, reduction = 'umap', group.by = "sctype0.3",label = T) + NoLegend()
umap05 <- DimPlot(dat, reduction = 'umap', group.by = "sctype0.5",label = T) + NoLegend()
umap07 <- DimPlot(dat, reduction = 'umap', group.by = "sctype0.7",label = T) + NoLegend()
umap1 <- DimPlot(dat, reduction = 'umap', group.by = "sctype1",label = T, pt.size = 1.5) + NoLegend()
grid.arrange(umap03, umap05, umap07, umap1, ncol = 2, nrow = 2,
             top = textGrob("sc type cell assinment - cell markers", gp=gpar(fontsize=20)))

pdf(file.path("figures/clustering", "scType_markers_umap.pdf"))
grid.arrange(umap03, umap05, umap07, umap1, ncol = 2, nrow = 2,
             top = textGrob("sc type cell assinment - cell markers", gp=gpar(fontsize=20)))
dev.off()

umap03 <- DimPlot(dat, reduction = 'umap', group.by = "sctypeRef0.3",label = T) + NoLegend()
umap05 <- DimPlot(dat, reduction = 'umap', group.by = "sctypeRef0.5",label = T) + NoLegend()
umap07 <- DimPlot(dat, reduction = 'umap', group.by = "sctypeRef0.7",label = T) + NoLegend()
umap1 <- DimPlot(dat, reduction = 'umap', group.by = "sctypeRef1",label = T) + NoLegend()
grid.arrange(umap03, umap05, umap07, umap1, ncol = 2, nrow = 2,
             top = textGrob("Harmony integration", gp=gpar(fontsize=20)))

pdf(file.path("figures/clustering", "scType_refMarkers_umap.pdf"))
grid.arrange(umap03, umap05, umap07, umap1, ncol = 2, nrow = 2,
             top = textGrob("sc type cell assinment - ref markers", gp=gpar(fontsize=20)))
dev.off()

umap1 <- DimPlot(dat, reduction = "umap", group.by = "DF.classifications", label = T) + NoLegend()
umap2 <- DimPlot(dat, reduction = 'umap', group.by = "sctype0.5",label = T) + NoLegend()
grid.arrange(umap1, umap2, ncol = 2, nrow = 1,
             top = textGrob("Batch Effects Investigation", gp=gpar(fontsize=20)))
```

```{r}
umapClus <- DimPlot(dat, reduction = 'umap' ,label = T, 
                    group.by = 'sctype0.5') + NoLegend()
umapTime <- DimPlot(dat, reduction = 'umap', 
                    group.by = "orig.ident",label = T)
grid.arrange(umapClus, umapTime,
             ncol = 2, nrow = 1,
             top = textGrob("Sc-Type stuff", gp=gpar(fontsize=20)))

DimPlot(dat, reduction = "umap", label = TRUE, group.by = 'sctypeRef0.5')  
DimPlot(dat, reduction = "umap", label = TRUE, group.by = 'sctype0.5')  

dat <- SetIdent(dat, value = "sctype1")
table(Idents(dat))
```



### heat map of assignment scores

```{r}

lowConfidenceClusters <- sctype_scores[sctype_scores$scores < 1000 ,]

for (i in c("0.3", "0.5", "0.7", "1")) {

  heatMapConfListRef[[i]]$cluster <- as.character(heatMapConfListRef[[i]]$cluster)
  heatMatrix <- matrix(0, nrow = length(unique(heatMapConfListRef[[i]]$type)), 
                       ncol = length(unique(heatMapConfListRef[[i]]$cluster)))
  rownames(heatMatrix) <- unique(heatMapConfListRef[[i]]$type)
  colnames(heatMatrix) <- unique(heatMapConfListRef[[i]]$cluster)
  
  for (j in 1:nrow(cL_resutls)) {
    cell_type <- heatMapConfListRef[[i]]$type[j]
    cluster <- heatMapConfListRef[[i]]$cluster[j]
    score <- heatMapConfListRef[[i]]$scores[j]
    
    if (cell_type %in% rownames(heatMatrix) && cluster %in% colnames(heatMatrix)) {
      heatMatrix[cell_type, cluster] <- score
    }
  }
  
  
  Ht <- Heatmap(
    heatMatrix,
    name = "Scores",
    cluster_rows = FALSE,
    cluster_columns = FALSE,
    color_space = "LAB",
    cell_fun = function(j, i, x, y, width, height, fill) {
      grid.rect(x, y, width, height, gp = gpar(col = "black", fill = NA))
    }
  )

  print(Ht)
  
}


for (i in c("0.3", "0.5", "0.7", "1")) {

  heatMapConfList[[i]]$cluster <- as.character(heatMapConfList[[i]]$cluster)
  heatMatrix <- matrix(0, nrow = length(unique(heatMapConfList[[i]]$type)), 
                       ncol = length(unique(heatMapConfList[[i]]$cluster)))
  rownames(heatMatrix) <- unique(heatMapConfList[[i]]$type)
  colnames(heatMatrix) <- unique(heatMapConfList[[i]]$cluster)
  
  for (j in 1:nrow(cL_resutls)) {
    cell_type <- heatMapConfList[[i]]$type[j]
    cluster <- heatMapConfList[[i]]$cluster[j]
    score <- heatMapConfList[[i]]$scores[j]
    
    if (cell_type %in% rownames(heatMatrix) && cluster %in% colnames(heatMatrix)) {
      heatMatrix[cell_type, cluster] <- score
    }
  }
  
  
  Ht <- Heatmap(
    heatMatrix,
    name = "Scores",
    cluster_rows = FALSE,
    cluster_columns = FALSE,
    color_space = "LAB",
    cell_fun = function(j, i, x, y, width, height, fill) {
      grid.rect(x, y, width, height, gp = gpar(col = "black", fill = NA))
    }
  )

  print(Ht)
  
}




Heatmap(
    heatMatrix[,as.character(lowConfidenceClusters$cluster)],
    name = "Scores",
    cluster_rows = FALSE,
    cluster_columns = FALSE,
    color_space = "LAB",
    cell_fun = function(j, i, x, y, width, height, fill) {
      grid.rect(x, y, width, height, gp = gpar(col = "black", fill = NA))
    }
  )
```

```{r}
umap1 <- DimPlot(dat, reduction = "umap", group.by = "DF.classifications", label = T) + NoLegend()
umap2 <- DimPlot(dat, reduction = 'umap', group.by = "sctype0.5",label = T) + NoLegend()
grid.arrange(umap1, umap2, ncol = 2, nrow = 1,
             top = textGrob("Batch Effects Investigation", gp=gpar(fontsize=20)))
```


#### markers - all clusters 

```{r}
#Markers <- FindAllMarkers(dat)
#Markers %>%
#    group_by(cluster) %>%
#    dplyr::filter(avg_log2FC > 1)

#OverExpressedMarkers <- Markers[Markers$avg_log2FC > 0 ,]
#UnderExpressedMarkers <- Markers[Markers$avg_log2FC < 0 ,]

#topMarkers <- list()
#topMarkersUnder <- list()
#clusIds <- levels(Markers$cluster)

#for (i in clusIds) {
#  topMarkers[[i]] <- head(OverExpressedMarkers[OverExpressedMarkers$cluster == as.character(i), ], 500)
#  topMarkersUnder[[i]] <- head(UnderExpressedMarkers[UnderExpressedMarkers$cluster == as.character(i), ], 500)
#}

#markersListUp <- bind_rows(topMarkers)
#markersListDown <- bind_rows(topMarkersUnder)

#write.csv(markersListUp, "processedData/good/allClusterMarkersUp.csv")
#write.csv(markersListDown, "processedData/good/allClusterMarkersDown.csv")

```


### organising meta-data

```{r}
head(dat@meta.data)
colnames(dat@meta.data)

#dat@meta.data$harmony.03 <- dat@meta.data$RNA_snn_res.0.3
#dat@meta.data$harmony.05 <- dat@meta.data$RNA_snn_res.0.5
#dat@meta.data$harmony.07 <- dat@meta.data$RNA_snn_res.0.7

#dat@meta.data <- dat@meta.data[, c("orig.ident", "nCount_RNA", "nFeature_RNA",  "qc.mito", "pANN", "DF.classifications", "PreHarmony05res", "sctypeRef0.3", "sctypeRef0.5", "sctypeRef0.7", "sctype0.3", "sctype0.5", "sctype0.7", "sctype1", "sctypeRef1")]
```

### markers items 

```{r}
acinar <- c("Angptl4", "Rarres2", "Cpb1", "Rbpjl", "Lyz3", "Olfm4", "Cela1", "Reg2", "Cela3b", "Clps", "Spink1", "Ptf1a", "Cel", "Aldob", "Pdzk1ip1", "Pla2g1b", "Reg3g", "Ctrb1", "AA467197", "Rnase1", "Try5", "Gdf15", "Klk1b16", "Anpep", "Pnliprp1", "Muc1", "Lgals2", "Klk1b11", "Pnlip", "Zg16", "Klk1b26", "Try4", "Cpa1", "Prss2", "Prss1l", "Cela2a", "Klk1b9", "Reg1", "Klk1b22", "Cxcl17", "Prss1", "Klk1b8", "Klk1b1", "Klk1b27", "Klk1b24", "Klk1", "Klk1b5", "Klk1b4", "Klk1b3", "Klk1b21", "Reg3d", "Reg3b", "Prss3l", "Prss3", "Try10", "Cpa2", "Cela3a", "Reg3a", "Sycn", "Cfb", "Gm20547")
ductal <- c("Aqp1", "Aldh1a3", "Slpi", "Wfdc2", "Mmp7", "Perp", "Hnf1b", "Krt19", "Cldn10", "Cldn1", "Serping1", "Tff2", "Tff1", "Pigr", "Ambp", "Spp1", "Pdx1", "Anxa4", "Pdlim3", "Tspan8", "Krt20", "Gdf15", "Cftr", "Serpina5", "Muc1", "Onecut1", "Lgals4", "Cfb", "Gm20547")
metaplastic <- c("Sox9", "Id3", "Krt19", "Runx1", "Krt18", "Kras", "Foxq1", "Muc1", "Onecut2", "Reg1", "Cox1", "Cox2", "Mist1", "Ptf1a")
```

### veiwing exocrine markers 

```{r}
dat <- SetIdent(dat, value = "sctype0.5")
DimPlot(dat, reduction = 'umap', group.by = "sctype0.5",label = T) + NoLegend()

DotPlot(dat, features = acinar, cols = c("red", "green")) + theme(axis.text.x = element_text(angle = 70, hjust = 1))
DotPlot(dat, features = ductal, cols = c("red", "green")) + theme(axis.text.x = element_text(angle = 70, hjust = 1))
DotPlot(dat, features = metaplastic, cols = c("red", "green")) + theme(axis.text.x = element_text(angle = 70, hjust = 1))

DotPlot(dat, features = c("Birc5", "Spc24", "Cdca3", "Cks2", "2810417H13rik", "Gpx2", "Top2a", "Cdk1", "Ube2c", "Cdca8", "Cenpf", "Tk1", "Ccnb2", "Cenpm", "Mki67", "Prc1", "Pbk", "Lockd", "Smc2", "Cenpw", "Ccna2", "Cdc20", "Racgap1", "Knstrn", "Cenpa", "Tpx2", "Kif23", "Spc25", "Rrm2", "Gins2"),
        cols = c("red", "green")) + theme(axis.text.x = element_text(angle = 70, hjust = 1))

DotPlot(dat, features = c("Onecut2", "Tspan8", "Ctse", "Pglyrp1", "Sfn", "Wfdc2", "Dmbt1", "Epcam", "Fxyd3", "Lgals4", "Krt19", "Vsig2", "Gsta4", "Elf3", "Atp1b1", "Cldn2", "Cldn7", "Muc1", "2200002D01Rik", "Gsto1", "Krt7", "Klf5", "Car2", "Prom1", "Gpx2", "Tm4sf4", "Stard10"),
        cols = c("red", "green")) + theme(axis.text.x = element_text(angle = 70, hjust = 1)) ## tumour 

DotPlot(dat, features = c("Birc5", "Spc24", "Cdca3", "Cks2", "2810417H13Rik", "Gpx2", "Top2a", "Cdk1", "Ube2c", "Cdca8", "Cenpf", "Tk1", "Ccnb2", "Cenpm", "Mki67", "Prc1", "Pbk", "Lockd", "Smc2", "Cenpw", "Ccna2", "Cdc20", "Racgap1", "Knstrn"),
        cols = c("red", "green")) + theme(axis.text.x = element_text(angle = 70, hjust = 1)) ## tumour 2

DotPlot(dat, features = c("Cldn3", "Tm4sf4", "Ambp", "Tstd1", "Dcdc2a", "Epcam", "Ces1d", "Cldn7", "Atp1b1", "Ttr", "Lurap1l", "Hhex", "Krt19", "Fxyd3", "Sox9", "Spint2", "Cldn10", "Wfdc15b", "Apoc1", "Kifc3", "Alcam", "Pdzk1ip1", "Cadm1", "Sorbs2", "Cxadr", "1700011H14Rik"),
        cols = c("red", "green")) + theme(axis.text.x = element_text(angle = 70, hjust = 1)) ## Ductal

DotPlot(dat, features = c("Pnliprp2", "Klk1", "Gp2", "Cpa2", "Cel", "Spink1", "Try10", "Pla2g1b", "Cuzd1", "Pdia2", "Dmbt1", "Erp27", "Serpini2", "Reg3d", "Tmed6", "Aqp12", "Ctrc", "Amy1", "Fkbp11", "Amy2a5", "Lcmt1", "Gcat", "Amy2a2", "Reg3b", "Hamp2"),
        cols = c("red", "green")) + theme(axis.text.x = element_text(angle = 70, hjust = 1)) ## Acinar 1

DotPlot(dat, features = c("Reg3g", "Spink1", "Reg3b", "Pnliprp2", "Klk1", "Gp2", "Erp27", "Try10", "Reg3a", "Gm2663", "Cckar", "Serpina10", "Bex2", "Cabp2", "Rbpjl", "Hsd17b13", "Ptf1a", "Gm4744", "Klk1b3", "tdTomato", "Pnliprp1", "Reg2"),
        cols = c("red", "green")) + theme(axis.text.x = element_text(angle = 70, hjust = 1)) ## Acinar 2

DimPlot(dat, reduction = "umap", label = T, group.by = "sctypeRef1")
DimPlot(dat, reduction = "umap", label = T, group.by = "sctype0.7")

```

```{r}
FeaturePlot(dat, features = c("Zg16", "Cpa1", "Krt19", "Krt18")) # acinar 
FeaturePlot(dat, features = c("Krt19", "Sox9", "Clu")) # ductal
FeaturePlot(dat, features = c("Nes", "Cd44", "Vim", "Cdkn2a")) # Nes progenitor
FeaturePlot(dat, features = c("Pou2f3", "Dclk1", "Trpm5")) # Tuft
FeaturePlot(dat, features = c("Chga", "Chgb", "Neurod1", "Syp", "Ppy", "Gcg", "Ins", "Sst")) # neuroendocrine like 
FeaturePlot(dat, features = c("Muc1", "Muc6", "Gkn3", "Muc5ac", "Tff2", "Tff1", "Agr2")) # Gastric

FeaturePlot(dat, features = c("Aldh1a1", "Aldh1", "Cd44", "Dclk1")) #  cancer stem cell
FeaturePlot(dat, features = c("Krt17", "Krt19", "Lamc2", "foxa1")) #  cancer stem cell

FeaturePlot(dat, features = c("Col1a1", "Rgs5", "Ptprc", "Pecam1"))

VlnPlot(dat, features = c("AF5060261"), group.by = "sctype0.5")
FeaturePlot(exCells2, features = c("AF5060261")) # clus 1 no KRAS but looks like ADM 
```

15, 10, 18, 24, 31, 19, 28, 30, 29  

```{r}
dat <- SetIdent(dat, value = "RNA_snn_res.0.3")

exCells <- subset(dat, idents = c("7", "13", "19"))
DimPlot(exCells, reduction = "umap", label = T)
DimPlot(dat, reduction = "umap", label = T, group.by = "RNA_snn_res.0.3")
DimPlot(exCells, reduction = "umap", label = T, group.by = "DF.classifications")
FeaturePlot(exCells, features = c("Zg16", "Cpa1")) # acinar 
FeaturePlot(exCells, features = c("Krt19", "Sox9", "Clu")) # ductal
table(Idents(exCells))
```

```{r}
saveRDS(dat, "FinaleProcessedData/6000HarmonyFullLabels.rds")
saveRDS(exCells, "FinaleProcessedData/6000ExCellsRaw.rds")
```
